### ISSUE TITLE
The new solve_substinence function error

### ISSUE THREAD

**Issue by whaleturtley** [ligonteaching/EEP153_Materials#5]
The new function now gives this error:
AttributeError: 'Series' object has no attribute 'magnitude'
When we try to add in new maxima.

**Comment by whaleturtley** [comment]
I'm now getting an invalid value error so I will probably try to troubleshoot this in class!

**Comment by ligon** [comment]
For the AttributeError: the issue is that you're passing in a vector of prices that don't have units/magnitudes.  

There are a couple of possible fixes.  First is to add units by applying `fooddatacentral.units`.  In the prototype I provided we do that like this:
```
   df['FDC Quantity'] = df[['Quantity','Units']].T.apply(lambda x : fdc.units(x['Quantity'],x['Units']))
   df['FDC Price'] = df['Price']/df['FDC Quantity']

   df.dropna(how='any') # Drop food with any missing data

   # To use minimum price observed
   Prices = df.groupby('Food',sort=False)['FDC Price'].min()
```

If your units are *already* in hectograms/deciliters so that you don't need to convert, you can still do the conversion just by replacing the first line with `df['FDC Quantity'] = df['Quantity'].apply(lambda x: fdc.units(x,'hectogram'))`.

An alternative would be to modify `solve_subsistence_problem` so that it could handle prices without units.  For example, replace the first line with
```
    try: 
        p = Prices.apply(lambda x:x.magnitude)
    except AttributeError:  # Maybe not passing in prices with units?
        warnings.warn("Prices have no units.  BE CAREFUL!  We're assuming prices are per hectogram or deciliter!")
        p = Prices

    p = p.dropna()
```
The problem with this solution (as the warning is meant to indicate) is that if we don't keep track of units we're adding a possible source of difficulty-to-track bugs.  Much better to keep proper track of your units.
